mirego/trikot

- trikot-viewmodels-declarative/sample/android/build.gradle.kts
Remove duplicate lifecycle-reactivestreams-ktx dependency in viewmodels-declarative sample for Android.
I noticed a duplicate dependency in trickot-viewmodels-declarative sample for Android, seems to be a copy/paste error.
> Remove duplicate lifecycle-reactivestreams-ktx dependency in samples.

- trikot-viewmodels/viewmodels/src/commonMain/kotlin/com/mirego/trikot/viewmodels/properties/Color.kt
NOTE: This PR is a copy of https://github.com/mirego/trikot.viewmodels/pull/116 (I have to make it again because the change got lost when the trikot mono-repo was created)
* Make the Color a data class so that it's easy to compare colors
* Add White and Black colors in the companion object since the
In my current project, we want to know if two colors are the same and the only way we can do that is to compares the red, green, blue and alpha values. This will not be necessary if we make the Color class a data class.
Also, black and white are colors that are commonly used throughout my project (and probably other projects) so having them in a companion object is quite useful so that we don't have to create a new instance every time we need one or the other.
All features has been …
> Convert Color class to data class

- trikot-viewmodels-declarative/swift/uikit/VMDUITextFieldExtensions.swift
We had a name clashing for Objective-C selectors between **trikot-viewmodel** & **trikot.viewmodel-declarative** using UIKit.
We bring back the fix that was lost when bringing trikot to mono repo https://github.com/mirego/trikot.viewmodels.declarative/pull/40
> Rename clashing Objective-C textfield selector

- trikot-viewmodels-declarative/swift/swiftui/Components/VMDTextField.swift
**Viewmodels Declarative iOS Components**
With Xcode 13.2.x when running on iOS 14 VMDTextField was crashing.
This is a workaround to avoir the crash until Xcode is fixed. Ref: https://github.com/gongzhang/swiftui-availability-check-crash
Tested in my project
> Workaround to fix a crash on iOS 14

- trikot-viewmodels/sample/common/src/commonMain/kotlin/com/trikot/viewmodels/sample/viewmodels/home/LabelsViewModel.kt
- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/LabelViewModelBinder.kt
- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/ViewModelBinder.kt
Not sure why the code was duplicated, but this is the only binder that does not call `View.bindViewModel(...)` internally. 
I realized this in my project when the new accessibility feature was not working only with labels on Android. It was already OK on iOS.
In the sample app.
> [ViewModel] Use bindViewModel in LabelViewModelBinder

- jenkins-jobs/release.groovy
In order to support a parallel release of trikot with kotlin native's new memory model (since #19), we need to be able to specify the target branch when releasing this library on jenkins.
> Support branch-specific release on jenkins

- trikot-streams/swift-extensions/TrikotPublisherExtensions.swift
Adds the ability to bind a publisher of value type `I` directly to a variable of type `V` by providing a transform block.
This enables a more streamlined way to deal with differences between shared code data types and native data types.
Usage exemple:
```swift
class SomeClass {
var location: CLLocationCoordinate2D
func setupBindings() {
bind(viewModel.location, \SomeClass.location) { (geoLoc: GeographicLocation) in
CLLocationCoordinate2D(latitude: geoLoc.latitude, longitude: geoLoc.longitude)
}
}
}
```
> [Streams] Add ability to bind a variable using an intermediate representation

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/extensions/ViewModelExtensions.kt
When observing a ViewModel asState, we now use the instance of the ViewModel as the key to decide if remember() must re-calculate the value.
The current implementation of observeAsState() uses the remember mechanism to remember the value.  The mechanism behind Remember() is that the value is "calculated" once, and if the UI is re-composed afterward, the same value will be used.
The problem with that approach here is that if we observeAsState a ViewModel, and the _instance_ of the viewmodel changes between two recomposition, the remembered state will not be recalculated with the new instance.
By using the ViewModel instance as the "rememberance" key, we make sure that we update the State.
> Fixed the method to observe a ViewModel as State (Jetpack Compose)

- CHANGELOG.md
- trikot-viewmodels-declarative/sample/ios/Sample/SampleImageProvider.swift
- trikot-viewmodels-declarative/swift/swiftui/Extensions/VMDImageResource+Extensions.swift
- trikot-viewmodels-declarative/swift/uikit/VMDImageResourceExtensions.swift
- trikot-viewmodels-declarative/viewmodels-declarative/src/iosMain/kotlin/com/mirego/trikot/viewmodels/declarative/configuration/VMDImageProvider.kt
Change `VMDImageProvider` return type to `UIImage` instead of `String`.
- Adds compile time safety when used in conjunction with a code generator like `SwiftGen` of `R.swift`
- Adds the ability to reference system images (ex: `UIImage(systemName: "heart.fill")`)
Tested integrated with the Sample App
> [VMD] Update VMDImageProvider's signature on iOS

- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/SubscriberFromBlock.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/reactive/SubscriberFromBlockTests.kt
This fixes an issue where `request` would never be called on subscribe.
`request` is usually used for backpressure management which we don't support but to be compliant with the spec, we must still request for Long.MAX_VALUE events. It marks the Publisher as "effectively unbounded".
This fix was required to be able to use coroutines interop https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-reactive
> Request unbounded events with subscribe extension

- trikot-viewmodels-declarative/swift/swiftui/Utilities/ObservableViewModelAdapter.swift
This is a small first step to be able to animate modification triggered by the common code. By passing an animation to the ObservableViewModelAdapter, all changes of the object will be animated.
In my project
> [VMD] Add the possibility to animate object change in ObservableViewModelAdapter

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
There was an extra Box layer wrapping the RemoteImage which was not being passed the received modifier so when passing a modifier with align properties the image was align within that extra box layer instead of within the VMDImage parent's layout.
We also add an option to add a different content scale for the placeholder image.
With the current implementation it is not possible to correctly align a VMDImage that is of RemoteImage type.
Tested with the sample app.
- [ x] Bug fix (non-breaking change which fixes an issue)
> [VMD] Fix android RemoteImage to allow alignment + add a placeholder content scale property

- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/button/ButtonShowcaseViewModelController.kt
- trikot-viewmodels-declarative/viewmodels-declarative/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/impl/VMDButtonViewModelImpl.kt
Having the VMDButtonViewModel actionBlock as a `var` was causing freezing exception if the ViewModel was freeze before setting the action. The ViewModel was frozen more often than we imagined, only binding a property on the ViewModel is freezing the ViewModel and all of the objects around 😬
A regression was introduce in a previous modification and that regression was generating crashes everywhere 😬
Tested in VMD sample project
> [VMD] Fix crash in VMDButtonViewModel

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
Add a new parameter on VMDImage to enable or disable hardware acceleration for an image
This is needed since we sometimes need to disable hardware acceleration for an image. In our case, we needed to disable it when we were taking an image of the screen
> Add a new parameter to allow or disable hardware acceleration on VMDImage

- trikot-viewmodels-declarative/swift/swiftui/ViewModelViewController.swift
This PR update the access control of `viewDidAppear(_:)` and `viewDidDisappear(_:)` to `open` so that it can be overridden in a subclass of `ViewModelViewController`.
This was tested in Sobeys project.
> [VMD] Move view controller lifecycle methods from public to open

- trikot-viewmodels/swift-extensions/UIButtonExtensions.swift
UIButton subclasses can now override `positionSubviews` to make further adjustments once layout was adjusted to respect the image's alignment.
I tested that a subclass of `UIButton` could override `positionSubviews`:
```
private class Test: UIButton {
override func positionSubviews(_ alignment: Alignment?) {
super.positionSubviews(alignment)
}
}
```
> [VM] Make UIButton extension positionSubviews overridable

- CHANGELOG.md
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/PublisherExtensions.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/processors/CollectProcessor.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/reactive/processors/CollectProcessorTests.kt
Collects items emitted by the source Publisher into a single data structure and returns a Publisher that emits this updated structure.
I had a use case in my app where I needed such an operator! 😄 
This has been fully unit tested and used in a production app here at Mirego
> [Streams] Introduce collect() operator for Publishers

- CHANGELOG.md
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/PublisherExtensions.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/processors/ScanWithProcessor.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/reactive/processors/ScanProcessorTests.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/reactive/processors/ScanWithProcessorTests.kt
Rename our newly added `Collect` processor to `ScanWith` as the current implementation actually responds to the [Scan](https://reactivex.io/documentation/operators/scan.html) reactive spec, not [Reduce/Collect](https://reactivex.io/documentation/operators/reduce.html).
This is a **breaking change** as the `Publisher.collect` extension is removed and because the `Publisher.scan` operator now properly dispatches the provided initial value on subscription.
This partially reverts changes of previous commit from https://github.com/mirego/trikot/pull/54
> [Streams] Rename Collect processor which is actually ScanWith

- trikot-viewmodels/swift-extensions/UIImageViewExtensions.swift
- trikot-viewmodels/swift-extensions/kingfisher/KFImageViewModelHandler.swift
We expose the downloadImageAdapter to the DefaultImageViewModelHandler so we can override the default behaviour.
We need to handle SVG image type, unfortunately UIKit does not handle SVG on is own. 
`UIImage(data: data)` with svg as data returns nil.
The solution is to expose a method `downloadImageAdapter` to let the applications handle the data itself.
The default behaviour remains the same and was tested here https://github.com/mirego/bellmedia-sports-mobile/pull/3654
> Expose downloadImageAdapter to DefaultImageViewModelHandler

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Versions.kt
- gradle.properties
Bump:
- AtomicFu from 0.17.0 to 0.17.1
- Jetpack Compose from 1.2.0-alpha03 to 1.2.0-alpha07
- Kotlinx.Coroutines from 1.6.0 to 1.6.1
- Ktor from 2.0.0-beta-1 to 2.0.0
- Kotlin to 1.6.20
> Bump dependencies

- trikot-viewmodels-declarative/compose/build.gradle.kts
Since source was not properly packaged, it was not possible to browser the code of all the VMD binding for jetpack compose, when used in a project.
> [VMD] Source was not properly packaged in the viewmodels-declarative-compose artefact

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyColumn.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyRow.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDList.kt
- trikot-viewmodels-declarative/sample/android/src/main/AndroidManifest.xml
- trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/home/HomeActivity.kt
- trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/list/ListShowcaseActivity.kt
- trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/list/ListShowcaseView.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/factories/SampleViewModelControllerFactory.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/factories/SampleViewModelControllerFactoryImpl.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/home/HomeNavigationDelegate.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/home/HomeViewModelController.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/list/ListShowcaseNavigationDelegate.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/list/ListShowcaseViewModel.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/list/ListShowcaseViewModelController.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/list/ListShowcaseViewModelImpl.kt
- trikot-viewmodels-declarative/sample/common/src/commonMain/resources/translations/translation.en.json
- trikot-viewmodels-declarative/sample/ios/Sample/UI/Home/HomeViewController.swift
- trikot-viewmodels-declarative/viewmodels-declarative/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/VMDListViewModel.kt
I added the following compose components for VMDListViewModel : VMDLazyColumn, VMDLazyColumnIndexed, VMDLazyRow and VMDLazyRowIndexed.
We have a generic VMDList component in compose that can only layout the list vertically, I think the naming is too generic because it assume we want to layout in a vertical list. I added VMDLazyColumn, VMDLazyColumnIndexed, VMDLazyRow and VMDLazyRowIndexed to allow layout in row or column and to have the ability to receive the index for example if we want to do a zebra list or add divider except for the last item etc.
I added a list showcase screen in the sample which uses those new components
- [x ] New feature (non-breaking change which adds functionality)
> [VMD] Add VMDLazyColumn and VMDLazyRow compose components + update android sample

- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/adapter/LifecycleAdapter.kt
- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/lifecycle/ApplicationStatePublisher.kt
Switch away from lifecycle observers with `OnLifecycleEvent` as they use reflection and are deprecated in favor of `DefaultLifecycleObserver`
Fix lifecycle viewmodel so that it moves to STOPPED state when view is detached from window and DESTROYED when holder is recycled / parent lifecycle is destroyed.
> [VM] Update lifecycle observers

- trikot-kword/README.md
- trikot-kword/kword/src/androidMain/kotlin/com/mirego/trikot/kword/android/PreviewI18N.kt
The default implementation of Android kword does not work properly in the context of the Jetpack Compose previewer (it cannot load the file since it's not running the in the same context than the actual app).
Having previews with the actual translations is useful.
In a project.
> [KWORD] Added an implementation of I18N that works with the Jetpack Compose Previewer.

- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/adapter/LifecycleAdapter.kt
- trikot-viewmodels/viewmodels/src/androidTest/kotlin/com/mirego/trikot/viewmodels/adapter/LifecycleAdapterTest.kt
This fixes a crash that would occur in certain conditions where lifecycle would be destroyed before onBind being called.
Also add some LifecycleAdapter unit test covering most of the scenarios.
Crash fixed and test coverage lacking
Via unit tests
> [VM] LifecycleAdapter lifecycle fixes and test coverage

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDButton.kt
If we want to customize the look of the tapped state (ripple) of a button, we have to be able to specify these two values. Their default values remain the same, so this change is transparent.
> [VMD] Added interactionSource and indication as optional parameters for VMDButton

- trikot-viewmodels-declarative/swift/swiftui/Components/VMDTextField.swift
The `$` symbol was missing from the earlier version.
> [VMD] Fix missing wrappers for VMDTextField

- CHANGELOG.md
- gradle.properties
- trikot-viewmodels/swift-extensions/UIButtonExtensions.swift
- trikot-viewmodels/swift-extensions/UIImageViewExtensions.swift
- trikot-viewmodels/swift-extensions/UILabelExtensions.swift
- trikot-viewmodels/swift-extensions/UIPickerExtensions.swift
- trikot-viewmodels/swift-extensions/UISliderExtensions.swift
- trikot-viewmodels/swift-extensions/UISwitchExtensions.swift
- trikot-viewmodels/swift-extensions/UITextFieldExtensions.swift
- trikot-viewmodels/swift-extensions/UITextViewExtensions.swift
- trikot-viewmodels/swift-extensions/UIViewExtensions.swift
All (or at least, the most used and problematic) public properties used for binding the ViewModels on `UIView` extensions are now prefixed with "trikot".
This prevents naming conflicts with host applications.
Tested in my application. A simple rename in all UIViews did the trick :).
> Prefix UIView extensions properties with "trikot" for viewmodels

- trikot-streams/coroutines-interop/build.gradle.kts
We fix couroutine interop test execution on a macos host by adding missing sourcesets configurations.
It wasn't failing previously on the CI pipeline as it is executed in a linux container.
Now, the CD pipeline uses a macos container so it runs tests on that platform targets.
Should fix CD
Locally on a macos host.
> Fix couroutine interop macos test configuration

- trikot-bluetooth/bluetooth/src/androidMain/kotlin/com/mirego/trikot/bluetooth/android/AndroidBluetoothManager.kt
We have several crashes with a project that uses trikot.bluetooth.
Here are different errors that all happen at the same place :
- Fatal Exception: java.util.ConcurrentModificationException
- Fatal Exception: java.util.NoSuchElementException
- Fatal Exception: java.lang.NegativeArraySizeException: -1
```
foundDevice.remove(result.device.address)
devicesPublisher.value = foundDevice.values.toList()
```
It seems to be a concurrency problem and since the standard HashMap doesn't handle access from multiple thread correctly, I changed the HashMap to use a ConcurrentHashMap instead.
In client app
> Use ConcurrentHashMap instead of normal HashMap in trikot.bluetooth

- trikot-analytics/analytics-viewmodel/src/commonMain/kotlin/com/mirego/trikot/analytics/TrackableViewModelAction.kt
- trikot-viewmodels/viewmodels/src/commonMain/kotlin/com/mirego/trikot/viewmodels/properties/ViewModelAction.kt
See title☝️ 
To fix a bug 😏 
Tested in my project
> TrackableViewModelAction wasn't calling the analytics when execute was called without arguments

- trikot-viewmodels-declarative-flow/compose-flow/build.gradle.kts
- trikot-viewmodels-declarative/compose/build.gradle.kts
The two modules had an un-conventional way of declaring the sourcesJas tasks. With this PR the maven metadata file is now also generated directly in the version folder, which could help locating sources inside the IDE.
Tested locally with another project and confirmed that the sources are still bundled correctly
> Cleanup sourcesJar tasks definition

- build.gradle.kts
- settings.gradle.kts
- trikot-foundation/test-utils/build.gradle.kts
- trikot-foundation/test-utils/src/commonMain/kotlin/com/mirego/trikot/foundation/timers/ConfigurableMockTimerFactory.kt
- trikot-foundation/test-utils/src/commonTest/kotlin/com/mirego/trikot/foundation/timers/ConfigurableMockTimerFactoryTest.kt
Add new ConfigurableMockTimerFactory that allows to simulate the time of timer. This allows to not ignore timers in test and assert that a certain delay has passed. 
`setTIme()` : Allows to set the timerFactory to a specific duration
`addToTime()`: Allows to add a certain duration to the timerFactory
In my project, I needed to assert something was null after a certain delay. After discussing with @mathieularue, he showed me he had this MockTimerFactory in another project. This motivated us to then move this code in Trikot since there was a need in two projects.
This has been both tested in this repo with a test class named `ConfirableMockTimerFactoryTest` and in my project.
> Add configurableMockTimerFactory

- CHANGELOG.md
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/factory/VMDComponents.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/content/VMDTextFlowImagePairContent.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/content/VMDTextPairFlowContent.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/extension/FlowExtensions.kt
Creating a text component with Flowi18N was not supported since the component expects a String. This PR now adds support to either use a Flow<String> or simply String for text components
In my project, I needed to use hacks to be able to show text using Flowi18N. This PR will simplify usage of the component factory.
This has been both tested in project and locally using samples. I did not push the modifications in the sample as to keep the sample light.
> Add support for Flowi18N when creating components using factory

- trikot-viewmodels-declarative/swift/swiftui/Components/VMDTextField.swift
We fix Xcode 14.0 compilation error
*Stored properties cannot be marked potentially unavailable with '@available'*
> Remove unavailable stored properties

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCircularProgressIndicator.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLinearProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCircularProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLinearProgressIndicator.kt
`VMDCircularProgressIndicator` was ignoring `color` and `strokeWidth` and `VMDLinearProgressIndicator` was ignoring `color` and `backgroundColor` properties when the progress was indeterminate.
Fix an incorrect behaviour
> [VMD] Fix Android progress views configuration propagation

- trikot-bluetooth/bluetooth/src/androidMain/kotlin/com/mirego/trikot/bluetooth/android/AndroidBluetoothManager.kt
Location is not required for **all** versions of Android to access Bluetooth devices.
For Android 12 and above, location is not required to scan Bluetooth devices. So it doesn't have to be considered a "missing permission".
I followed the [Bluetooth permissions documentation](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions) provided by Android
We have an application that is using Bluetooth on Android 12 and 13 and we want to avoid having to request the location permission when it's not required.
We're using the  `missingPermissionsPublisher` to check if we can start scanning, and since it's not empty we can't scan. We could build a workaround on our side but the proper way should be to have the right "missing" permissions in Trikot.
> Update Bluetooth permission requirements for Android depending on OS version

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/impl/VMDButtonViewModelImpl.kt
Fix an issue with setAction with a flow where it would stay subscribed to the flow and potentially re-trigger the action.
VMD (publishers) dealt with this by using first() so similarly we do get the first value (if available) and call the action with it.
When migrating our project from VMD to VMD-flow, this bug was found and it had the side effect to re-trigger our actions multiple times.
It no longer stay subscribed after the fix.
> [VMD-flow] Fix ButtonViewModel setAction staying subscribed

- trikot-analytics/analytics/src/commonMain/kotlin/com/mirego/trikot/analytics/AnalyticsService.kt
- trikot-analytics/analytics/src/commonMain/kotlin/com/mirego/trikot/analytics/AnalyticsServiceLogger.kt
- trikot-analytics/analytics/src/commonMain/kotlin/com/mirego/trikot/analytics/EmptyAnalyticsService.kt
- trikot-analytics/firebase-ktx/src/main/java/com/mirego/trikot/analytics/FirebaseAnalyticsService.kt
- trikot-analytics/mixpanel-ktx/src/main/java/com/mirego/trikot/analytics/MixpanelAnalyticsService.kt
- trikot-analytics/swift-extensions/firebase/FirebaseAnalyticsService.swift
- trikot-analytics/swift-extensions/mixpanel/MixpanelAnalyticsService.swift
This PR add a new function on the AnalyticsService that expose the distinct id that the external provider uses to identify a device. It needs to be exposed as a `Promise` since the Android Firebase implementation expose the property as a async Task.
Some of `Mixpanel` APIs requires the distinctId.
This has been tested in my project.
> Add distinctAppId to the AnalyticsService

- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
We add a check on the bitmap size too prevent crashing later in the drawing process if the size exceeds the limit set by Android.
When downloading remote images there was no check on the resulting drawable size, so anywhere using remote images it could crash due to this limitation.
This has been tested in an ongoing development app that we encountered the issue.
> Prevent crashing on too large bitmap in VMDImage on Android

- trikot-datasources/datasources/src/commonMain/kotlin/com/mirego/trikot/datasources/BaseHotDataSource.kt
- trikot-datasources/datasources/src/commonTest/kotlin/com/mirego/trikot/datasources/BaseExpiringDataSourceTests.kt
- trikot-datasources/datasources/src/commonTest/kotlin/com/mirego/trikot/datasources/BaseHotDataSourceTests.kt
Changes the way `BaseHotDataSource` handles its first read() for cases where a cache datasource is used
The actual implementation of `BaseHotDataSource`, during its first read(), always returns the value returned by its internal cacheDataSource, no matter its state. This led to two unexpected behaviors:
**Error case**
If the cacheDataSource returns an "error" DataState (which is the case at first read() since cache file does not exist on disk), this error would be very briefly returned as the result of the actual read() method of the datasource (which is incorrect at that level). Usually this would go unnoticed since the internalRead() method quickly returns a pending state after. The sequence of the states emitted by the data source would be something like that:
1. Error state (no data) …
> [Datasources] Improvement to BaseHotDataSource

- gradle.properties
- trikot-datasources/datasources-flow/src/commonMain/kotlin/com/mirego/trikot/datasources/flow/BaseFlowDataSource.kt
- trikot-datasources/datasources-flow/src/commonMain/kotlin/com/mirego/trikot/datasources/flow/DiskCacheFlowDataSource.kt
- trikot-datasources/datasources-flow/src/commonTest/kotlin/com/mirego/trikot/datasources/flow/BaseFlowDataSourceTests.kt
Fix an issue where we did not emit pending while refreshing the data
In some cases, we want to be notified that the data is refreshing.
Added a unit test
> [Datasource flow] Fix pending state while refreshing

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
Add a way to pass a callback in order to receive the async image state externally
It happens often in our projects that we need to know when the remote image is loaded in order to trigger an event in the UI
This has been tested locally in a in-development project
> Add callback to RemoteImage in VMDImage to know when the resource is loaded on Android

- .github/workflows/cd.yml
- .github/workflows/release.yml
We changed CD and release jobs to run on macos-11 since it doesn't work on macos-12
The actual problem is the similator name now having parenthesis according to this :
https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
And the kotlin gradle plugin requires the name without parenthesis
it was fixed in https://github.com/JetBrains/kotlin/commit/10947e2c45255cf89b8cee1598017b6fc61b0079
but it is not released yet.
Fixes builds on github action
> Force github action builds on macos 11

- trikot-datasources/datasources-flow/src/commonMain/kotlin/com/mirego/trikot/datasources/flow/BaseFlowDataSource.kt
- trikot-datasources/datasources-flow/src/commonTest/kotlin/com/mirego/trikot/datasources/flow/BaseFlowDataSourceTests.kt
We had an issue with ExecutableDataFlow with an upstream datasource of DiskCacheDataSource where it would not return the data after the read if someone called clear concurrently
The following happened:
coroutine 1 - ExecutableDataFlow.clear()
coroutine 2 - ExecutableDataFlow.read()
clear cancels the previous cached flow
cancellation of the cached flow bubbles up to our read job.
read emited pending but no data
Now we make sure everything is behind the mutex so that it waits until clear is complete to perform the read which will create a new cached flow since the previous one was removed.
We had a race condition which prevented the data from receiving data.
Added a unit test that reproduced the original issue, it now passes.
Also tested in the read code.
> [DataSource.flow] Fix a race condition with clear+read and delete+read

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLifecycleView.kt
- trikot-viewmodels-declarative-flow/swift/swiftui/Extensions/VMDView+Lifecycle.swift
Lifecycle handling in VMD flow platform code was not properly reacting to "background / foreground" switch.
Putting an app in background didn't call `onDisappear()`, and bringing it back to foreground didn't call `onAppear()`. These two cases are valid and should be handled properly.
Side-note: the iOS implementation wasn't even usable, it was not `public`.
Code extracted from a projet currently in production.
- [x ] New feature (non-breaking change which adds functionality)
> [VMD-FLOW] Improved handling of lifecycle on both android and iOS

- .github/workflows/cd.yml
- build.gradle.kts
In the current CD workflow, a new dev version is built and published for each new commit in master branch. However, this would only release the "maven" artefacts. For project using cocoapod, the new release would not be available since it requires that a tag is added on github.
This adds an extra step to properly create and push the tag.
The usual flow was manually create a tag each time a new releases was needed. Now it is automatic.
> Added step in CD workflow to add a tag when publishing a new DEV version (needed for cocoapod)

- trikot-datasources/datasources-flow/src/commonMain/kotlin/com/mirego/trikot/datasources/flow/BaseFlowDataSource.kt
Previously we were cancelling the cached data flow job when invalidating the cache via delete or clear. 
That had the side effect to cancel all pending reads as well if both were launched at the same time (since the Cancellation did bubble up to the parent scope).
We found that this behavior was not really what we wanted to achieve. Now we no longer cancel the child job so that concurrent reads can continue. We also now start by clearing the cache before clearing the upstream so that local cache is cleared faster.
In some cases we did call clear and followed quickly by read. The clear did take some time to complete (due to IO with a file datasource) and read started while clear was running. Once clear completed, it cancelled the job, and the read was cancelled because of that.
> [DataSourceFlow] Change delete/clear cache cancellation behavior

- trikot-bluetooth/bluetooth/src/androidMain/kotlin/com/mirego/trikot/bluetooth/android/AndroidBluetoothManager.kt
Make toList conversion thread safe by cloning map before converting its values to list.
When we had a single element that we were removing from the map because we lost its signal, we would sometimes try to convert values to list in a non-thread-safe access.
The `toList()` implementation works like this:
```
public fun <T> Iterable<T>.toList(): List<T> {
if (this is Collection) {
return when (size) {
0 -> emptyList()
1 -> listOf(if (this is List) get(0) else iterator().next())
else -> this.toMutableList()
}
}
return this.toMutableList().optimizeReadOnlyList()
}
```
In the case where the size of `values` was determined to be 1, if we lost the signal at that point, the value would be removed in the map, and `iterator().next()` would crash.
The solution is to use the copy-constructor to copy …
> [Bluetooth] Make found devices copy thread safe.

- gradle.properties
- trikot-kword/kword-plugin/src/main/groovy/com/mirego/kword/KWordExtension.groovy
We change the way the project is stored inside the extension. Previously we kept the whole project in member, but this is prohibited when enabling the configuration cache feature since Project is not serializable.
In order to enable configuration cache in a project, every plugins used need to be compatible.
This has been tested locally on another project
> Support Gradle configuration cache for KWord plugin

- README.md
[Trikot.patron](https://github.com/mirego/trikot.patron) has been deprecated in favour of our new [kmp-boilerplate](https://github.com/mirego/kmp-boilerplate)
> Replace mentions of `trikot.patron` by `kmp-boilerplate`

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/impl/VMDListViewModelImpl.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelImpl.kt
The VMDAnimationContext was completely broken in VMD Flow. The push / peek / pop sequence assumes that the willChange and didChange methods are synchronous, since they weren't, nothing was working.
I fixed that by use tryEmit on the MutableSharedFlow and changing buffer overflow strategy to avoid any failed emit.
In my project
> Fix animation in VMD Flow

- .github/workflows/cd.yml
- .github/workflows/release.yml
- build.gradle.kts
Stop using the release plugin, use publish and tag instead
We were previously using the release plugin which was bumping versions automatically in git.
With the new release process, we want to manage the bumping of versions manually instead.
Not at all, we'll test after it's merged !
> Remove publish gradle plugin

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelDSL.kt
- trikot-viewmodels-declarative/viewmodels-declarative/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelDSL.kt
Some projects were using the buttonWithText() DSL with a closure at the end. When specifying an action in that closure it ended up not being set correctly. This is because the function has a default action parameter that was applied after the closure. We make sure to call the closure at the end of the apply block so the components can be configured correctly.
> Fix closure assignation overriden by default params in DSL

- trikot-viewmodels-declarative-flow/sample/common/TRIKOT_FRAMEWORK_NAME.podspec
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/home/HomeViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/animation/types/AnimationTypesShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/button/ButtonShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/image/ImageShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/list/ListShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/picker/PickerShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/progress/ProgressShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/snackbar/SnackbarShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/textfield/TextFieldShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/toggle/ToggleShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/build.gradle.kts
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/androidMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/androidMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/factory/AndroidViewModelProviderFactory.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/iosArm32Main/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/iosMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/iosSimulatorArm64Main/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/jsMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/jvmMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/tvosMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/VMDPlatformViewModelController.kt
VMDViewModelController on Android was managing its own coroutineScope instead of using the lifecycle provided scope.
Ensure that a lifecycle managed scope is used on Android.
In the sample app.
Breaking change is mostly due to the renaming of the scope, to fix, rename `viewModelControllerScope` to `viewModelScope`. The new name is more consistent with what the scope does, view model controller manages the lifecycle events for the view model, providing a scope to the view model. It's therefore the scope of the view model.
> [VMD-flow] Use of the viewModelScope on Android

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/androidMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/ViewModelFragment.kt
- trikot-viewmodels-declarative/viewmodels-declarative/src/androidMain/kotlin/com/mirego/trikot/viewmodels/declarative/controller/ViewModelFragment.kt
We override onResume() and onPause() in ViewModelFragment in order to call the matching methods on VMDViewModelController.
The onAppear() and onDisappear() methods were not plugged in the ViewModelFragment class. They were only called in ViewModelActivity.
> Add missing lifecycle methods in ViewModelFragment

- README.md
Our link had the content and URL parts mixed up. I also took the time to tweak the whole sentence 🙂
> Fix kmp-boilerplate link in README.md

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
This change enables the developper to put nullable content descriptions for images
Some images are not important enough to require talkback. When forcing an empty string, the talkback responds with "Unlabeled image". Using `null`, however, skips the talkback for that image
Tested using the sample with several values for contentDescription, such as "Hello", "", null. Everything works as expected
> Make ContentDescription nullable on android

- buildSrc/src/main/kotlin/Versions.kt
- trikot-viewmodels-declarative-flow/compose-flow/build.gradle.kts
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/extensions/ImageResourceExtensions.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/androidMain/kotlin/com/mirego/trikot/viewmodels/declarative/configuration/VMDImageProviderConfiguration.kt
The default Jetpack Compose `painterResource` only handle vector drawables and rasterized assets. Attempting to use any other type of Drawable will result in this error:
```
java.lang.IllegalArgumentException: Only VectorDrawables and rasterized asset types are supported ex. PNG, JPG
at androidx.compose.ui.res.PainterResources_androidKt.loadVectorResource(PainterResources.android.kt:94)
at androidx.compose.ui.res.PainterResources_androidKt.painterResource(PainterResources.android.kt:65)
at com.mirego.trikot.viewmodels.declarative.compose.extensions.ImageResourceExtensionsKt.painterResource(ImageResourceExtensions.kt:21)
```
Since our `VMDImageProvider` is generic and always uses the default `painterResource`, it is not allowed to map a `VMDImageResource` to an XML drawable or a nine-patch …
> [VMD-Flow] Compose: added optional support for XML Drawables and 9-patch

- trikot-viewmodels-declarative-flow/sample/common/build.gradle.kts
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDButton+Configuration.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDButton.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDForEach.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDButton+Configuration.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDButton.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDForEach.swift
**VMDForEach**
Useful when you want to display a VMDListViewModel in SwiftUI but you don't want to put it in a List (VMDList)
**New VMDButton feature**
Sometime we need to trigger some native code when a VMDButton action is triggered. The new externalActionHandler allow the caller, when the button is tapped, to do stuff before or after the VMDButton action.
PS: Modification done in VMD and VMD-flow
I was using these 2 features in all of my projects so why not moins that in Trikot.
> iOS: Add VMDForEach and externalActionHandler on VMDButton

- trikot-viewmodels-declarative-flow/swift/swiftui/Extensions/VMDAnimation+Extensions.swift
- trikot-viewmodels-declarative/swift/swiftui/Extensions/VMDAnimation+Extensions.swift
The name `Animation` can clash with the same name from other libraries. Prefixing it to avoid clashing.
> [VMD-swift] Prefixed Animation usage to avoid name clash

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDTextField.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDTextField.swift
Initialize the SwiftUI `VMDTextField`'s text property using `viewModel.text`.
Setting an initial text on `VMDTextFieldViewModel` was broken in SwiftUI. The text field was always empty upon initialization.
Tested using the sample applications.
> Fix SwiftUI VMDTextField initial text

- trikot-streams/coroutines-interop/src/commonTest/kotlin/kotlinx/coroutines/reactive/FlowAsPublisherTest.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/processors/SharedProcessor.kt
I had a case where this flow as publisher below wasn't emitting any values. 
```        
val publisher = flowOf(1)
.map { n ->
n
}
.asPublisher()
.shared()
publisher.subscribe(CancellableManager()) {
//No emmited value
}
```
Our `SharedProcessor` is a subscriber, therefore it should call `request(n: Long)` on its subscription. 
We use a lot of interoperability between flow and publisher, and this was causing several issues with our shared publishers. 
Test has been added into `FlowAsPublisherTest` to make sure the behaviour of the `SharedProcessor` hasn't changed after the interop.
> Fix SharedProcessor interop with Flow

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDTextField.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDTextField.swift
The initial value displayed in the SwiftUI TextField wasn't transform with the transform, now it is !
> Apply the text transofrm also in the initial value

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
Since we are using coil `rememberAsyncImagePainter` instead of `AsyncImage`, we are losing a few built-in features such as sampling in the image request decoding.
This passes `size` and `scale` parameters in the image request which will later be used to calculate the sample size. The size is a `ConstraintsSizeResolver` which will passed as a modifier for contraints to be resolved. This is a similar strategy employed in coil with `AsyncImage`.
**NOTE:** The `Image` is now nested within a `Box` and takes a block with a `BoxScope` as a receiver. If you are using that, you might want to switch your placeholder modifiers to match parent `Box`.
When large source images are provided, the image decoding could be slower and take more memory. This was due to the whole image being loaded even though …
> [VMD] Fix image sampling on android

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/factory/VMDComponents.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelDSL.kt
Fix binary compatibility with text component factory
The method signature changes in #149 made the API not binary compatible with the previous releases.
With a slight change, the API is now binary compatible.
Tested for binary compatibility with another project
One day we should really put some time and define the public API + validate it against https://github.com/Kotlin/binary-compatibility-validator
> [VMD] Fix binary compatiblity with Text Component Factory

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
When complex placeholder is not required, rely on AsyncImage.
Using AsyncImage from coil is more efficient at measures and drawing. When there's no need to use a complex placeholder, we use this instead of having our own rendering with rememberAsyncImagePainter.
The placeholder is handled with a painter.
We're profiling and testing VMDImage with different Constraints. Turns out AsyncImage handles most of the constraints out of the box and is generally more efficient than we we currently have in VMD.
Tested in sample app and in another app.
Changes should be ABI compatible and no changes should be needed to use the most efficient binding.
> [VMD] Bind VMDImage with coil AsyncImage when complex placeholder is not required

- Trikot.podspec
- trikot-viewmodels-declarative-flow/sample/ios/Podfile.lock
- trikot-viewmodels-declarative/sample/ios/Podfile.lock
Update Kingfisher required version to 7.6.2
Kingfisher dependency now fails compilation following a Swift compiler bug fix. [Fix](https://github.com/onevcat/Kingfisher/commit/75041a4e0c6a5ac6f16e5ff7fdd975d92ec32c10)
Both VMD sample apps build and run on Xcode 14.3 RC2 (same as release).
Updated a dependency
> Trikot VMD iOS: Update Kingfisher required version to 7.6.2

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/extensions/ViewModelExtensions.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/extensions/ViewModelExtensions.kt
In this case, reflection is used to call the getter. Calling it without any parameters doesn't work anymore, probably following an update of the Kotlin version at some point.
Adding the required param to the getter.
Attempting to observe a single field without an initial value (which is optional) resulted in a crash:
```
java.lang.IllegalArgumentException: Callable expects 1 arguments, but 0 were provided.
at kotlin.reflect.jvm.internal.calls.Caller$DefaultImpls.checkArguments(Caller.kt:20)
at kotlin.reflect.jvm.internal.calls.CallerImpl.checkArguments(CallerImpl.kt:15)
at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:112)
at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
at …
```
> [VMD-Compose] Fixed observe of a single field of a ViewModel without specifying an initial value explicitly. 

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/Versions.kt
- gradle/wrapper/gradle-wrapper.properties
- trikot-analytics/mixpanel-ktx/src/main/java/com/mirego/trikot/analytics/MixpanelAnalyticsService.kt
- trikot-viewmodels-declarative-flow/sample/android/build.gradle.kts
- trikot-viewmodels-declarative/sample/android/build.gradle.kts
- trikot-viewmodels/sample/android/build.gradle.kts
Trikot should try to keep minimum android version requirements as low as possible, so that legacy projects that still use 21 as their min SDK can use it.
There is nothing in the code that actually requires a min SDK of 24.
Some older projects still have their min SDK set at 21, and this should not prevent us from including Trikot.
Android samples are still running, all check tasks still pass, lib can be included in a 21+ project with success.
> Lowering Android min SDK to 21

- trikot-foundation/trikotFoundation/src/commonMain/kotlin/com/mirego/trikot/foundation/date/Date.kt
- trikot-foundation/trikotFoundation/src/iosMain/kotlin/com/mirego/trikot/foundation/date/Date.kt
- trikot-foundation/trikotFoundation/src/jsMain/kotlin/com/mirego/trikot/foundation/date/Date.kt
- trikot-foundation/trikotFoundation/src/jvmShared/kotlin/com/mirego/trikot/foundation/date/Date.kt
Deprecate `com.mirego.trikot.foundation.date` in favor of [`kotlinx-datetime`](https://kotlinlang.org/api/kotlinx-datetime)
As `com.mirego.trikot.foundation.date` doesn't offer much flexibility and we don't we to recreate the official Kotlin library, we recommend to use [`kotlinx-datetime`](https://kotlinlang.org/api/kotlinx-datetime)
See Mirego Slack discussions:
* [#Trikot](https://mirego.slack.com/archives/CK4CXSXLM/p1682591710066669)
* [#Kotlin](https://mirego.slack.com/archives/C5B1UTKUH/p1682545911551079)
N/A
> Deprecate com.mirego.trikot.foundation.date in favor of kotlinx-datetime

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/FormattedVisualTransformation.kt
- trikot-viewmodels-declarative/compose/build.gradle.kts
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/FormattedVisualTransformation.kt
- trikot-viewmodels-declarative/compose/src/test/kotlin/com/mirego/trikot/viewmodels/FormattedVisualTransformationTest.kt
When visual transformation changes the length of the original string the offset mapping must consider added characters before the given offset.
Example: A NIV "ABCDEFGHI" formatted as "ABC DEF GHI"
**Offset from original to formatted:**
0 -> 0
4 -> 5
8 -> 10
Unit tests
> Fix Android visual transformation offset mapping

- trikot-http/http/src/commonMain/kotlin/com/mirego/trikot/http/requestPublisher/HttpRequestPublisher.kt
In TrikotHttp, when using HttpRequestPublisher the values of cachePolicy and followRedirects were always fallback back to the default values.
> [TrikotHttp] cachePolicy and followRedirects values were lost in HttpRequestPublisher

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDForEach.swift
- trikot-viewmodels-declarative/swift/swiftui/Components/VMDForEach.swift
iOS `VMDForEach` conformance change.
`DynamicViewContent` is a SwiftUI protocol introduced in iOS 13. It is documented as:
> A type of view that generates views from an underlying collection of data.
Making `VMDForEach` conform to `DynamicViewContent` enables access to the following SwiftUI APIs:
- `func onDelete(perform: Optional<(IndexSet) -> Void>) -> some DynamicViewContent`
- `func onInsert(of: [UTType], perform: (Int, [NSItemProvider]) -> Void) -> some DynamicViewContent`
- `func onMove(perform: Optional<(IndexSet, Int) -> Void>) -> some DynamicViewContent`
[API Documentation](https://developer.apple.com/documentation/swiftui/dynamicviewcontent)
Its sole requirement is exposing a public [data property](https://developer.apple.com/documentation/swiftui/dynamicviewcontent).
This …
> iOS: Make `VMDForEach` conform to `DynamicViewContent`

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCheckbox.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDSwitch.kt
Toggleable semantic was added to the parent composable (VMDLabeledComponent) in order to make the whole component tappable and selectable via TalkBack.
This change was done to properly support A11y talkback on VMDToggleButton.
In sample app
> [VMD-Flow Android] Add toggleable to VMDCheckbox and VMDSwitch

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDPicker.swift
Add missing binding of the Picker component in SwiftUI
Add missing binding from #170 
Within the demo app
> Bind VMDPickerViewModel to Picker swiftUI

- buildSrc/src/main/kotlin/Versions.kt
- trikot-kword/kword-plugin/build.gradle.kts
- trikot-kword/kword-plugin/src/main/groovy/com/mirego/kword/KWordEnumGenerate.groovy
Fix issue with kotlin poet recent versions which no longer accept override modifier on the constructor parameter, which is legit. We move it to the property which result in the same generated code.
Fixes https://github.com/mirego/trikot/issues/174
Was able to reproduce locally with kotlin poet latest version, validated the fix too.
> [Kword-plugin] Update kotlin poet to latest + fix code generation

- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/extension/FlowExtensions.kt
Fix a crash that could occurred on iOS with the FlowExtensions wrap method if the flow value type is nullable.
In order to fix that, we add support for nullable type.
To fix a crash on iOS.
Tested in a project.
> [trikot-viewmodels-declarative-flow] Fix crash in FlowExtensions wrap method

- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/lifecycle/ApplicationStatePublisher.kt
Android `Lifecycle::addObserver` and `Lifecycle::removeObserver` should only be called on the main thread, this PR makes sure that these functions are always called on the main thread.
This was somewhat unclear in Trikot and could cause crashes in apps subscribing to the ApplicationStatePublisher when subscribing/unsubscribing. Trikot should make sure that these functions are called from the main thread.
Tested in my application.
> Dispatch Android Lifecycle addObserver and removeObserver on main thread

- trikot-viewmodels/viewmodels/build.gradle.kts
- trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/InputTextViewModelBinder.kt
Fix binary compatibility with viewmodels that was broken in #177
The R class and databinding class was generated in package `com.mirego.trikot.viewmodels` instead of `com.mirego.trikot.viewmodels.android`
We want to preserve binary compatibility
Opened the jar file. But we really need to add binary compatibility checks.
> [ViewModels] Fix binary compatibility with viewmodels

- README.md
- buildSrc/src/main/kotlin/Versions.kt
- trikot-streams/coroutines-interop/src/commonMain/kotlin/kotlinx/coroutines/reactive/Await.kt
- trikot-streams/coroutines-interop/src/commonMain/kotlin/kotlinx/coroutines/reactive/Channel.kt
- trikot-streams/coroutines-interop/src/commonMain/kotlin/kotlinx/coroutines/reactive/Publish.kt
- trikot-streams/coroutines-interop/src/commonTest/kotlin/kotlinx/coroutines/reactive/AwaitCancellationStressTest.kt
Bump kotlinx.coroutines to 1.7.3
Cherry pick relevant changes from jetbrains upstreams reactive sources.
Note: 1.6.4 and 1.7.3 are incompatible due to internal `LinkedListChannel` having been removed but this should be invisible to consumers of the lib.
Keeping things up to date.
Via Unit tests
> [streams-interop] Bump kotlinx.coroutines to 1.7.3

- trikot-viewmodels-declarative-flow/swift/core/VMDFlowUtils.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/Snackbar/VMDSnackBarStateObject.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Utilities/ObservableViewModelAdapter.swift
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/extension/FlowExtensions.kt
Tag `5.0.0-dev2660` introduced a breaking change to `VMDFlow` for iOS apps.
The generated Objective-C header for VMDFlow's watchBlock method now always specifies that the value argument is an optional:
```
- (void)watchBlock:(void (^)(T _Nullable, id<PREFIXCloseable>))block __attribute__((swift_name("watch(block:)")));
```
This PR:
- Changes VMDFlow's kotlin signature from `class VMDFlow<T : Any?>` to `class VMDFlow<out T>`
- Fixes trikot-viewmodels-declarative-flow swift files to account for this change.
- **It does not remove the nullability of watched values.**
Fixes compilation issues on iOS apps.
Changes were built locally and tested against a production project.
> VMDFlow declaration change and optional values handling on iOS

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDButton.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDButton.kt
Assign Role.Button semantics by default for VMDButton and allow customization
On android, VMDButton implementation uses a Box and a clickable modifier. By default the role on the clickable modifier is null (no role). This will give Button role to all VMDButton by default and allow to override it if needed instead of the contrary (needing to set Button role each time).
In sample
> [VMD] VMDButton button role on Android

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDButton.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDForEach.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDList.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDPicker.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDProgressView.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDText.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDTextField.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDToggle.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/ViewModifiers/VMDModifier.swift
I found a regression in VMDViewModel Flow SwiftUI components, the field "isHidden" is no longer binded.
I choose to pass the 2 fields to the vmdModifier instead of observing the VM in the ViewModifier to avoid any small performance issue of observing the propertyWillChange 2 times for each component.
Tested in my project.
> VMDViewModel Flow: Fix Swift isHidden binding

- trikot-bluetooth/swift-extensions/TrikotAttributeProfileCharacteristic.swift
- trikot-bluetooth/swift-extensions/TrikotAttributeProfileService.swift
- trikot-bluetooth/swift-extensions/TrikotBluetoothDevice.swift
- trikot-bluetooth/swift-extensions/TrikotBluetoothManager.swift
- trikot-bluetooth/swift-extensions/TrikotBluetoothScanResult.swift
Since the switch to the new memory model, the iOS Bluetooth library contained compilation errors:
> - Cannot find 'behaviorSubject' in scope
> - Cannot find 'frozenSubject' in scope
To fix the errors, the way the `subject` and `behaviorSubject` are initialized has been changed.
This change was tested in a project using Bluetooth.
> Fix Bluetooth iOS compile errors

- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDTextField.kt
- trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
- trikot-viewmodels-declarative-flow/sample/common/TRIKOT_FRAMEWORK_NAME.podspec
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
Add a VMDImage signature that allow to pass custom loading and placeholder composable.
The current implementation of RemoteImage that is used when the placeholder param is passed always load a fullscale Image in memory regardless of the view's size (unless size is hardcoded).
The current implementation also does not allow to have a different loading UI than the placeholder / error UI.
I plugged an image in the sample using this signature and a similar version was used in DavidsTea project.
I did no remove any prior implementation / signature
- [ x] New feature (non-breaking change which adds functionality)
> [VMD-Flow Android]  Add a VMDImage that allow custom loading and error placeholder composable

- CHANGELOG.md
- buildSrc/src/main/kotlin/Versions.kt
Update Ktor to 2.3.3 and Atomicfu to 0.22.0
Fix error `e: Old Kotlin/JS compiler is no longer supported. Please migrate to the new JS IR backend` caused by old Ktor version
See [KTOR-5543 KTOR-5544 Update Kotlin to 1.8 #3398](https://github.com/ktorio/ktor/pull/3398)
Demo apps
> Update Ktor to 2.3.3 and Atomicfu to 0.22.0

- trikot-kword/sample/ios/Sample/Collector.swift
Fix kword sample, FlowCollector signature changed in latest kotlinx.coroutines version.
Sample did not compile
Ran the sample
> [Kword] Fix ios sample after kotlinx-couroutines signature change

- build.gradle.kts
Fix CD workflow.
CD disables samples and since binary compatibility plugin cannot find the ignored projects it fails. This prevents from adding those project while samples are disabled.
CD was broken due to https://github.com/mirego/trikot/pull/190
Ran `./gradlew apiCheck -Pdisable_samples`
> Fix CD/Release workflow

- trikot-streams/streams/api/android/streams.api
- trikot-streams/streams/api/jvm/streams.api
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/PublisherExtensions.kt
- trikot-viewmodels-declarative-flow/compose-flow/api/compose-flow.api
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDHtmlText.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/html/CharacterStyle.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/html/HtmlText.kt
- trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/html/MetricAffectingSpan.kt
- trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/text/TextShowcaseActivity.kt
- trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/text/TextShowcaseView.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseNavigationDelegate.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModel.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModelController.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModelImpl.kt
- trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModelPreview.kt
- trikot-viewmodels-declarative-flow/sample/ios/Sample/UI/Showcase/Components/Text/TextShowcaseView.swift
- trikot-viewmodels-declarative-flow/sample/ios/Sample/UI/Showcase/Components/Text/TextShowcaseViewController.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDHtmlText.swift
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/api/android/viewmodels-declarative-flow.api
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/api/jvm/viewmodels-declarative-flow.api
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/VMDHtmlTextViewModel.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/factory/VMDComponents.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/impl/VMDHtmlTextViewModelImpl.kt
- trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelDSL.kt
Renders html text (a subset of html tags) in a Text component in switui / compose. Rendering differ slightly on both platforms but is generally more performant than using a full fledged webview.
Needed to render a list of html blocks interlaced with other type of views.
Added sample
> [VMD-Flow] VMDHtmlTextViewModel / VMDHtmlText

- trikot-viewmodels-declarative-flow/sample/ios/Sample/UI/Home/HomeView.swift
- trikot-viewmodels-declarative-flow/sample/ios/Sample/UI/Home/HomeViewController.swift
- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDHtmlText.swift
In the case where a trikot based project is currently migrating from `trikot.viewmodels` to `trikot.viewmodel-declarative` there is a name clash in `VMDHtmlText.swift` between SwiftUI.Color and TRIKOT_FRAMEWORK_NAME.Color
I also improved the look and feel of the sample in dark mode while at it.
| Before | After |
|--------|--------|
| ![Screenshot 2023-10-25 at 6 19 43 PM](https://github.com/mirego/trikot/assets/87188/abb7d3ea-4e37-461c-aaf4-076464e9aa62) | ![Screenshot 2023-10-25 at 6 21 26 PM](https://github.com/mirego/trikot/assets/87188/27d8ef79-b0ba-4533-b8f0-2e4a2612c800) | 
To fix a blocking problem for projects that use both versions of the viewModel
Ran the sample app
> Prevent color name clash between swiftui and trikot.viewmodel

- trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDHtmlText.swift
In the case where a Trikot based project is currently migrating from trikot.viewmodels to trikot.viewmodel-declarative there is a name clash in VMDHtmlText.swift between SwiftUI.Font and TRIKOT_FRAMEWORK_NAME.Font
To fix a blocking problem for projects that use both versions of the viewModel
Ran the sample app and tested in my projects the changes
> Fix/prevent color name clash between swiftui and trikot.viewmodel font class

- trikot-viewmodels-declarative-flow/swift/swiftui/TrikotViewModelDeclarative.swift
Since the release of xcode 15, previews have stopped working as soon as you use a VMDImageResources. This is caused by a weird, undocumented xcode preview behaviour where it seems to change process so the `TrikotViewModelDeclarative.shared` instance gets recreated. 
This was detected by printing the object address at each access.
Using  `EnvironmentValues` to inject the `imageProvider` and the `spanStyleProvider` was explored and it does fix the problem, but requires a lot of boilerplate to get the provider and pass it to each view creating an image. No easy solution was found quickly
While we come up with a better solution (or, IF it is considered a bug in xcode, Apple fixes the problem 🤞🏻) this PR at least stops the preview from crashing and displays an ugly fallback image instead
To …
> Fix crashing previews in xcode 15

- trikot-kword/kword-remote-update/src/commonMain/kotlin/com/mirego/trikot/kword/remote/update/internal/RemoteTranslationsFetcher.kt
In a previous PR https://github.com/mirego/trikot/pull/208, I wrapped parallel HTTP requests inside a CoroutineScope. This means that one HTTP request failure will cause all the other requests to fail, which is not the intended behavior.
To fix this issue, each async task within the CoroutineScope is wrapped inside a supervisorScope to prevent parent job to be cancelled if the request fails.
> [KwordRemoteUpdate] Add supervisorScope to prevent cancellation of parallel http requests

- trikot-viewmodels/swift-extensions/UITextFieldExtensions.swift
When using the Kotlin 1.9.21 the Kotlin Native compiler now adds an underscores to the helper function execute.
We now call the full function `execute(actionContext: Any?)` with the argument `nil` to keep the same behaviour and fix the name clash.
> Fix name clash when using Kotlin 1.9.21

- CHANGELOG.md
- trikot-viewmodels-declarative/compose/api/compose.api
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDButton.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCheckbox.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCircularProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLabeledComponent.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyColumn.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyRow.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLinearProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDList.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDSwitch.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDText.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDTextField.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/material3/VMDCircularProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/material3/VMDLinearProgressIndicator.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/material3/VMDSwitch.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/material3/VMDText.kt
- trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/material3/VMDTextField.kt
For Jetpack Compose components, update parameters order so that mandatory parameters come before `modifier` parameters. 
According to [Jetpack Compose guidelines](
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter):
_Element functions MUST accept a parameter of type Modifier. This parameter MUST be named “modifier” and MUST appear as the first optional parameter in the element function's parameter list._ 
Convention seems to put mandatory parameters before `modifier` parameter.  (See official Compose components such as `Text()`, `Image()`)...
Rational: 
This allows to use the component by passing the `viewModel` parameter without specifying parameter name:
``` …
```
> refactor: Set Compose modifier as first optional parameter

- trikot-foundation/trikotFoundation/api/android/trikotFoundation.api
- trikot-foundation/trikotFoundation/api/jvm/trikotFoundation.api
- trikot-foundation/trikotFoundation/src/commonMain/kotlin/com/mirego/trikot/foundation/concurrent/AtomicReference.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/cancellable/CancellableManagerProvider.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/cancellable/CancellableManagerProviderTests.kt
A long lived CancellableManagerProvider could easily end up with very many “cancelled” Cancellable in it’s internal CancellableManager because this is only cleared when the Provider itself is cancelled.
This can cause huge memory leaks in some cases, for example in the DebounceProcessor
Since there is only ever one “not cancelled” CancellableManager provided by the CancellableManagerProvider, there is actually no need to keep the previously provided, now cancelled, CancellableManager.
We now simply use the internalCancellableManagerRef.
Also took the oportunity to make cancelPreviousAndCreate hopefully atomic be exposing and using getAndSet on AtomicReference
In certain realtime application, usage of `debounce()` on long lived, shared publishers could cause immense memory leaks
- Tested …
> Fix possibly huge memory leak caused by long lived CancellableManagerProvider

- trikot-graphql/graphql/src/commonMain/kotlin/com/mirego/trikot/graphql/QueryEscaping.kt
The `String.escapeForGraphql()` extension function was creating countless String objects inside the "fold" loop.
In my app, the query was huge, which means that many many String objects were allocated and deallocated about 100ms later, triggering many garbage collecting events. In an older device with low RAM and/or processing power, this could noticeably freeze the UI (in my case, for about 8 seconds!)
This fix was tested in my project. We no longer allocate many String objects, instead using a StringBuilder.
> Fix memory alloc bug when using trikot-graphql

- CHANGELOG.md
- Trikot.podspec
- trikot-viewmodels-declarative-flow/sample/ios/Podfile.lock
- trikot-viewmodels-declarative/sample/ios/Podfile.lock
- trikot-viewmodels/sample/ios/Podfile.lock
This updates Kingfisher to 7.10.1.
Kingfisher now includes the new required reason API privacy manifest which will be required by Apple in spring 2024.
Tested in the sample apps.
> Update Kingfisher to 7.10.1

- trikot-datasources/datasources-core/api/android/datasources-core.api
- trikot-datasources/datasources-core/api/jvm/datasources-core.api
- trikot-datasources/datasources-core/src/commonMain/kotlin/com/mirego/trikot/datasources/StateData.kt
Add a typealias StateData to DataState to avoid having to always specify the error type
Less keystrokes more thinking :wesmart:
In my project
> Datasource: Add typealias StateData

- trikot-http/swift-extensions/TrikotHttpResponse.swift
Changed the syntax to build a String dictionary in iOS
For some reason, the syntax used before to init the Strings map in TrikotHttpError causes error in building my iOS app.  
```
ios/Pods/Trikot/trikot-http/swift-extensions/TrikotHttpResponse.swift:16:23: cannot call value of non-function type '[AnyHashable : String.Type]'
var headers = [String: String]()
```
The app is not working locally without this change. So fixing it locally allowed me to build the app.
> change init of Strings dictionary in iOS in TrikotHttpResponse

- trikot-datasources/datasources-flow-filesystem/api/android/datasources-flow-filesystem.api
- trikot-datasources/datasources-flow-filesystem/api/jvm/datasources-flow-filesystem.api
- trikot-datasources/datasources-flow-filesystem/src/commonMain/kotlin/com/mirego/trikot/datasources/flow/generic/FileSystemDataSource.kt
- trikot-datasources/datasources-flow-filesystem/src/commonTest/kotlin/com/mirego/trikot/datasources/flow/generic/FileSystemDataSourceTests.kt
- Add a way to skip read and save data for a specific request. To do so, you have to subclass FileSystemDataSource and override shouldSkipRequest.
- Implement the delete method.
Tested in my project
> FileSystemDataSource ++

- trikot-kword/kword-plugin/src/main/kotlin/com.mirego.kword/KWordEnumGenerate.kt
Fix issue with kword directory which should have been marked as output directory instead of input.
Fixes this error when the directory does not exist
```
> Task :app:shared:kwordGenerateEnum FAILED
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':app:shared:kwordGenerateEnum' (type 'KWordEnumGenerate').
- In plugin 'mirego.kword' type 'com.mirego.kword.KWordEnumGenerate' property 'generatedDir' specifies directory 'generated' which doesn't exist.
Reason: An input file was expected to be present but it doesn't exist.
Possible solutions:
1. Make sure the directory exists before the task is called.
2. Make sure that the task which produces the directory is declared as an input.
For more information, please refer to …
```
> [Kword] Generated dir error

- Trikot.podspec
Added deployment target for macOS (OS X). I still needed to add a deployment target for iOS in the main spec, not sure if it's the right way to do it since some subspec has one.
Need macOS target support for the Pod.
It has been tested in an Xcode project with an iOS and a macOS target with a Podfile as this:
```ruby
require_relative 'podspec_versions.rb'
ENV['TRIKOT_FRAMEWORK_NAME']='Shared'
target 'AppForiOS' do
use_frameworks!
platform :ios, '15.0'
trikotVersion = properties['versions']['trikot']
pod 'Trikot/kword', :path => '../../trikot', :inhibit_warnings => true
end
target 'AppForMac' do
use_frameworks!
platform :macos, '12.0'
trikotVersion = properties['versions']['trikot']
pod 'Trikot/kword', :path => '../../trikot', :inhibit_warnings => true
end
```
> Add deployment target for iOS and macOS in podspec

- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/processors/CombineLatestProcessor.kt
- trikot-viewmodels-declarative-flow/sample/common/build.gradle.kts
- trikot-viewmodels-declarative/sample/common/build.gradle.kts
Make sure cancel and subscribe is also done on the queue. When used in conjunction with `Kotlinx.Flow` where cancellation is way more common, we ended up occasionally crashing in the CombineLatestProcessor with indexOfBounds errors in the publisherValues list
Example callstack:
```
Caused by java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.util.Objects.checkIndex(Objects.java:359)
at java.util.ArrayList.get(ArrayList.java:434)
at com.mirego.trikot.streams.reactive.processors.CombineLatestProcessor$CombineProcessorProcessorSubscription.updatePu …
```
> Fix thread safety problem surfaced when used in heavy multithreaded usage in a flow interop scenario

- trikot-streams/streams/api/android/streams.api
- trikot-streams/streams/api/jvm/streams.api
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/cancellable/CancellableManager.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/cancellable/CancellableManagerProvider.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/cancellable/VerifiableCancelledState.kt
- trikot-streams/streams/src/commonMain/kotlin/com/mirego/trikot/streams/reactive/promise/Promise.kt
- trikot-streams/streams/src/commonTest/kotlin/com/mirego/trikot/streams/cancellable/CancellableManagerTests.kt
Introduce the possibility to clean `Cancellable`s that have already been cancelled in a `CancellableManager`.
It's possible to have a global `CancellableManager` that accumulates a huge number of child `Cancellable` during the lifecycle of an app. When we cancel the massive list of `Cancellable`, it can be very performance heavy and can freeze on some lower-end devices.
We can now manually clean up the `queueList` of a `CancellableManager` by choosing the right moment to do it.
I also wanted to make sure that it could support Promises. Previously, a finished** Promise was still kept in the `queueList` until the provided `CancellableManager` was cancelled. (I like to call it the parent CancellableManager)
Now, a Promise that has received a result is considered "cancelled" and ready to be …
> Add cleanCancelledChildren on CancellableManager

- CHANGELOG.md
- trikot-kword/kword-plugin/api/kword-plugin.api
- trikot-kword/kword-plugin/src/main/kotlin/com.mirego.kword/KWordExtension.kt
- trikot-kword/kword-plugin/src/main/kotlin/com.mirego.kword/KWordPlugin.kt
The property `translationFile` was replaced with `translationFiles` to support multiple translation files.
Instead of
```kotlin
translationFile = file("src/commonMain/resources/translations/translation.en.json")
enumClassName = "com.mirego.sample.KWordTranslation"
generatedDir = file("src/commonMain/generated")
```
Do this
```kotlin
translationFiles.setFrom(file("src/commonMain/resources/translations/translation.en.json"))
enumClassName.set("com.mirego.sample.KWordTranslation")
generatedDir.set(file("src/commonMain/generated"))
```
`translationFiles` was already available in `KWordExtension`, but it was not possible to only set `translationFiles` without 
any `translationFile`. This error was returned on keys generation :
```
Cannot query the value of extension 'kword' property …
```
> Support multiple translation files with kword

- trikot-viewmodels-declarative-compiler/viewmodels-declarative-compiler-core/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compiler/BaseVMDCodeGenerator.kt
Fix file dependency declaration in viewmodels-declarative-compiler-core
In `BaseVMDCodeGenerator`,` codeGenerator.createNewFile()` is called without declaring any dependency. 
However, any generated ViewModel has at least one dependency to declare to allow KSP incremental build to work properly. 
We had build issue on CI after migrating from Kotlin 2.0 to Kotlin 2.2. 
After investigation, I found that KSP cache was behaving strangely and that almost none of the Impl classes were present in `generated/ksp/metadata`. 
With this fix, classes seems to be generated as expected.
Not enough, just make the build on CI pass. How do you intend to test this KSP plugin? 
AFAIK there is no sample project for it.
> Fix file dependency declaration in viewmodels-declarative-compiler-core
