trikot-viewmodels-declarative/viewmodels-declarative/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/components/impl/VMDButtonViewModelImpl.kt
Refactor VMDButtonViewModel action block to remove unnecessary overhead
Fixes #33 
Tested in sample project
=> [VMD] Refactor VMDButtonViewModel action block to remove unnecessary overhead

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/Targets.kt, trikot-analytics/analytics-viewmodel/build.gradle.kts, trikot-analytics/analytics/build.gradle.kts, trikot-bluetooth/bluetooth/build.gradle.kts, trikot-datasources/datasources/build.gradle.kts, trikot-foundation/trikotFoundation/build.gradle.kts, trikot-graphql/graphql/build.gradle.kts, trikot-http/http/build.gradle.kts, trikot-kword/kword/build.gradle.kts, trikot-streams/coroutines-interop/build.gradle.kts, trikot-streams/streams/build.gradle.kts, trikot-viewmodels/viewmodels/build.gradle.kts
Remove some duplication when declaring the same KMM targets in several modules
Just some cleanup, re-defining the same targets over and over.
=> [Build cleanup] Remove targets duplication

.gitignore, build.gradle.kts, trikot-analytics/analytics-viewmodel/build.gradle.kts, trikot-analytics/analytics/build.gradle.kts, trikot-analytics/firebase-ktx/build.gradle.kts, trikot-analytics/mixpanel-ktx/build.gradle.kts, trikot-bluetooth/bluetooth/build.gradle.kts, trikot-datasources/datasources/build.gradle.kts, trikot-foundation/trikotFoundation/build.gradle.kts, trikot-graphql/graphql/build.gradle.kts, trikot-http/http/build.gradle.kts, trikot-kword/kword-plugin/build.gradle.kts, trikot-kword/kword/build.gradle.kts, trikot-streams/coroutines-interop/build.gradle.kts, trikot-streams/streams/build.gradle.kts, trikot-streams/test-utils/build.gradle.kts, trikot-viewmodels-declarative/compose/build.gradle.kts, trikot-viewmodels-declarative/sample/common/build.gradle.kts, trikot-viewmodels-declarative/viewmodels-declarative/build.gradle.kts, trikot-viewmodels/sample/common/build.gradle.kts, trikot-viewmodels/viewmodels/build.gradle.kts
Configure the same repositories for all projects
=> [Build cleanup] Configure the same repositories for all projects

buildSrc/src/main/kotlin/Versions.kt, trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt, trikot-viewmodels-declarative/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/image/ImageShowcaseView.kt
Update to coil 2.0.0-rc03
The new API has some breaking changes so if you are using coil 1.X.X in your applications you will have to migrate as well.
=> [VMD] Update to coil 2.0.0-rc03

CHANGELOG.md
This adds more information in the changelog concerning the new UIView extensions "trikot" prefix in `4.0.0`.
=> Add more information in changelogs for Trikot 4.0.0 UIView extensions

README.md
Add dev release badge
Add CD badge
This makes it a bit easier to retrieve the latest dev release version
=> Add dev release badge to README.md

CHANGELOG.md
Add missing changelog entry for breaking change introduced in #88
=> Add missing changelog entry for breaking change introduced in #88

trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
This is the exact same fix as https://github.com/mirego/trikot/pull/99, but for flow!
=> Prevent crashing on too large bitmap in VMDImage on Android

trikot-viewmodels-declarative-compiler/viewmodels-declarative-compiler-flow/build.gradle.kts, trikot-viewmodels-declarative-compiler/viewmodels-declarative-compiler-flow/src/test/kotlin/com/mirego/trikot/viewmodels/declarative/compiler/FlowVMDCodeGeneratorTest.kt, trikot-viewmodels-declarative-compiler/viewmodels-declarative-compiler-flow/src/test/kotlin/com/mirego/trikot/viewmodels/declarative/compiler/TestReflectionUtil.kt
As suggested by @npresseault , added unit tests to the VMD Compiler using the `Kotlin Compile Testing` lib (https://github.com/tschuchortdev/kotlin-compile-testing)
VMD compiler was not unit tested. Having some tests will increase maintainability.
=> [VMD-Compiler] Added unit tests for VMD Compiler

trikot-viewmodels-declarative-compiler/viewmodels-declarative-compiler-core/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compiler/BaseVMDCodeGenerator.kt
When VMD Compiler is unable to resolve a class, the error thrown is not very helpful as to what and where the issue is.
The call to `resolve().toTypeName()` on an unknown type throws a generic error. We now validate the type before using to throw a more useful exception.
Additionally, current VM metadata is logged as well.
Before:
```
[ksp] java.lang.IllegalArgumentException: Error type '<ERROR TYPE>' is not resolvable in the current round of processing.
at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:61)
at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName(ksTypes.kt:55)
at com.squareup.kotlinpoet.ksp.KsTypesKt.toTypeName$default(ksTypes.kt:53)
at com.mirego.trikot.viewmodels.declarative.compiler.BaseVMDCodeGenerator.generateConstructor(BaseVMDCodeGenerator.kt:100)
``` …
=> [VMD-Compiler] Added better error message when something goes wrong

trikot-viewmodels/viewmodels/src/androidMain/kotlin/com/mirego/trikot/viewmodels/ImageViewModelBinder.kt
When using `ImageViewModelBinder.bind` on Android with a transformation, the binder doesn't apply transformation on drawable, it only applies to url image.
To be consistent, transformation must apply to all image sources.
Tested with local publishing. Usage example:
```
ImageViewModelBinder.bind(
binding.blurredBackgroundImageView,
viewModelController.viewModel.contentImageBackground,
lifecycleOwnerWrapper,
BlurTransformation(
requireContext(),
TypedValue.applyDimension(TypedValue.COMPLEX_UNIT_DIP, 26.8f, resources.displayMetrics).toInt()
)
)
```
=> Add missing transformation on drawable

CHANGELOG.md
It's this time of the year when we need to stamp an official release! 
Let's write the official 4.0.0 changelog and build a release ASAP.
We wish to facilitate the integration and migration for everyone and use an official version within our production-ready libraries and products.
=> Add complete 4.0.0 changelog

CHANGELOG.md, buildSrc/src/main/kotlin/Versions.kt
A missing piece following the latest Kotlin update to `1.7.20` in PR #135. We wish to use latest Kotlin Wrappers Extensions.
=> Use latest Kotlin Wrappers extensions

trikot-viewmodels-declarative-flow/swift/swiftui/ViewModelViewController.swift, trikot-viewmodels-declarative/swift/swiftui/ViewModelViewController.swift
The wrong super method was called in ViewModelController 😬
=> Call the right super method in viewDidDisappear

trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/extensions/ModifierExtensions.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDBasicTextField.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDButton.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCheckbox.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDCircularProgressIndicator.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDDropDownMenu.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyColumn.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLazyRow.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDLinearProgressIndicator.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDList.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDSwitch.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDText.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDTextField.kt, trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/button/ButtonShowcaseViewModelImpl.kt, trikot-viewmodels-declarative-flow/sample/common/src/commonMain/kotlin/com/mirego/sample/viewmodels/showcase/components/text/TextShowcaseViewModelImpl.kt, trikot-viewmodels-declarative-flow/sample/ios/Podfile.lock, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDButton.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDForEach.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDList.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDProgressView.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDText.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDTextField.swift, trikot-viewmodels-declarative-flow/swift/swiftui/Components/VMDToggle.swift, trikot-viewmodels-declarative-flow/swift/swiftui/ViewModifiers/VMDModifier.swift, trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModel.kt, trikot-viewmodels-declarative-flow/viewmodels-declarative-flow/src/commonMain/kotlin/com/mirego/trikot/viewmodels/declarative/viewmodel/VMDViewModelImpl.kt
Introduce `testIdentifier` as a nullable field in VMDViewModel and apply it to all VMD Components.
Introduce vmdModifier which will contain all base modifiers of VMDViewModel (`hidden` and `testIdentifier` for now).
`accessibilityIdentifier` and `testTag` are modifiers that can be used to retrieve a compose node or swiftui view during ui tests.
In the sample app
=> [VMD-Flow] Test identifiers

trikot-viewmodels-declarative/README.md
Simply to help new comers find it
=> Add link to the compiler documentation

buildSrc/src/main/kotlin/Versions.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt, trikot-viewmodels-declarative/compose/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDImage.kt
Bump coil to 2.5.0
We were on a release candidate and there was additional breaking changes that were introduced in later versions.
Ran samples
=> Bump coil to 2.5.0

trikot-analytics/swift-extensions/firebase/FirebaseAnalyticsService.swift
I'm not sure why the orignal syntax is no longer building in my setup 🤷🏼‍♂️ 
Be able to use the lib 
Tested in my project
=> Fix Swift dictionary init

trikot-kword/sample/common/build.gradle.kts, trikot-viewmodels-declarative-flow/sample/common/build.gradle.kts, trikot-viewmodels-declarative/sample/common/build.gradle.kts
Update kword plugin in sample apps
=> Update kword plugin in sample apps

trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/VMDHtmlText.kt, trikot-viewmodels-declarative-flow/compose-flow/src/main/kotlin/com/mirego/trikot/viewmodels/declarative/compose/viewmodel/internal/html/HtmlText.kt, trikot-viewmodels-declarative-flow/sample/android/src/main/java/com/mirego/sample/ui/showcase/components/text/TextShowcaseView.kt
Using URLAnnotation will allow the VoiceOver to provide "actions" for each of the links in a section of text. 
Tested using the components preview.
=> Use URLAnnotation for proper accessibility on Android.
